library("sqldf")
students = read.csv(file.choose(),header=TRUE)
sqldf("select * from students")
sqldf("select count(*) from students")
sqldf("select name,marks from students where marks>50")
sqldf("select * from students where marks<24")
sqldf("select * from students where name='A'")
sqldf("select DISTINCT Name from students ")
min(students$marks)
max(students$marks)
sum(students$marks)
nrow(students)
ncol(students)
nrow(students[students$marks==33,])
nrow(students[students$marks>33,])
sqldf("select * from students where marks==89")
sqldf("select * from students where marks>67 and rollno>3")
